server:
    port:8085
spring:
  profiles: development
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:10.34.51.17}:${MYSQL_PORT:3306}/${DB_EXAM:exam}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
#       boot:
#          admin:
#            client:
#              url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:9186}/admin
#             username: ${ADMIN_USERNAME:admin}
#              password: ${ADMIN_PASSWORD:11}
#              instance:
#                service-base-url: http://${USER_SERVICE_HOST:localhost}:${server.port}
#                metadata:
#                  tags:
#                    environment: prd

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS